# Generated by Django 3.2.15 on 2022-09-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthHub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='run_distance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='run_time',
            field=models.TimeField(default=0),
            preserve_default=False,
        ),
    ]
