# Generated by Django 3.2.15 on 2022-09-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthHub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthstats',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='healthstats',
            name='run_distance',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
