# Generated by Django 3.2.15 on 2022-09-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthHub', '0002_auto_20220910_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='run_distance',
            field=models.IntegerField(default=5),
        ),
    ]
