# Generated by Django 3.2.15 on 2022-10-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthHub', '0003_alter_healthstats_run_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthstats',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
